# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 290, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 70, 241, 191))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(420, 70, 241, 191))
        self.label2.setAutoFillBackground(False)
        self.label2.setFrameShape(QtWidgets.QFrame.Box)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(470, 290, 131, 41))
        self.pushButton2.setObjectName("pushButton2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuOperasi_Titik = QtWidgets.QMenu(self.menubar)
        self.menuOperasi_Titik.setObjectName("menuOperasi_Titik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOperasi_Pencerahan = QtWidgets.QAction(MainWindow)
        self.actionOperasi_Pencerahan.setObjectName("actionOperasi_Pencerahan")
        self.actionSimple_Contrast = QtWidgets.QAction(MainWindow)
        self.actionSimple_Contrast.setObjectName("actionSimple_Contrast")
        self.actionContrast_Stretching = QtWidgets.QAction(MainWindow)
        self.actionContrast_Stretching.setObjectName("actionContrast_Stretching")
        self.actionNegative_Image = QtWidgets.QAction(MainWindow)
        self.actionNegative_Image.setObjectName("actionNegative_Image")
        self.actionBiner_Image = QtWidgets.QAction(MainWindow)
        self.actionBiner_Image.setObjectName("actionBiner_Image")
        self.menuOperasi_Titik.addAction(self.actionOperasi_Pencerahan)
        self.menuOperasi_Titik.addAction(self.actionSimple_Contrast)
        self.menuOperasi_Titik.addAction(self.actionContrast_Stretching)
        self.menuOperasi_Titik.addAction(self.actionNegative_Image)
        self.menuOperasi_Titik.addAction(self.actionBiner_Image)
        self.menubar.addAction(self.menuOperasi_Titik.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Load Citra"))
        self.pushButton2.setText(_translate("MainWindow", "Proses Citra"))
        self.menuOperasi_Titik.setTitle(_translate("MainWindow", "Operasi Titik"))
        self.actionOperasi_Pencerahan.setText(_translate("MainWindow", "Operasi Pencerahan"))
        self.actionSimple_Contrast.setText(_translate("MainWindow", "Simple Contrast"))
        self.actionContrast_Stretching.setText(_translate("MainWindow", "Contrast Stretching"))
        self.actionNegative_Image.setText(_translate("MainWindow", "Negative Image"))
        self.actionBiner_Image.setText(_translate("MainWindow", "Biner Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
